version: '3.7'

services:
    mysql:
        container_name: adm_imdb_card_game_mysql
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=imdb_card_game
        security_opt:
            - seccomp:unconfined
        ports:
            - "3306:3306"
        networks:
            - imdb_network

networks:
    imdb_network: